extends Node
## Autoload script that initializes GDK at startup and manages lifecycle.
## Reads configuration from sample_config.cfg (generated by tools/setup_sample.ps1).

var config := ConfigFile.new()

func _ready() -> void:
	print("=== GodotGDK Bootstrap ===")
	print("GDK Version: ", GDK.get_version())

	# Load sample configuration
	var err = config.load("res://sample_config.cfg")
	if err != OK:
		push_error("[GDK] sample_config.cfg not found! Run tools/setup_sample.ps1 first.")
		return

	# Connect signals
	GDK.connect("initialized", _on_gdk_initialized)
	GDK.connect("error_occurred", _on_gdk_error)
	GDKUser.connect("user_signed_in", _on_user_signed_in)
	GDKUser.connect("sign_in_failed", _on_sign_in_failed)
	GDKUser.connect("user_signed_out", _on_user_signed_out)
	GDKInput.connect("device_connected", _on_device_connected)
	GDKInput.connect("device_disconnected", _on_device_disconnected)

	# Initialize GDK runtime
	err = GDK.initialize()
	if err != OK:
		push_error("GDK initialization failed: %s" % error_string(err))

func _on_gdk_initialized() -> void:
	print("[GDK] Runtime initialized!")

	# Initialize Xbox Live services with SCID from config
	var scid = config.get_value("xbox_live", "scid", "")
	if scid.is_empty():
		push_warning("[GDK] No SCID configured — achievements will not work")
	else:
		var scid_err = GDKAchievements.initialize(scid)
		if scid_err == OK:
			print("[GDK] Xbox Live services ready")

	# Initialize GameInput
	var input_err = GDKInput.initialize()
	if input_err == OK:
		print("[GDK] GameInput ready, devices: ", GDKInput.get_connected_device_count())

	# Try silent sign-in
	GDKUser.sign_in_silently()

func _on_gdk_error(message: String) -> void:
	push_error("[GDK] Error: " + message)

func _on_user_signed_in(user) -> void:
	print("[GDK] User signed in successfully")

func _on_sign_in_failed(error: String) -> void:
	push_warning("[GDK] Sign-in failed: " + error)

func _on_user_signed_out() -> void:
	print("[GDK] User signed out")

func _on_device_connected(joy_id: int) -> void:
	print("[GDK] Controller connected: joy ", joy_id)

func _on_device_disconnected(joy_id: int) -> void:
	print("[GDK] Controller disconnected: joy ", joy_id)

func _process(delta: float) -> void:
	# Dispatch GDK async callbacks
	GDK.tick()

	# Poll GameInput
	GDKInput.process()

func _exit_tree() -> void:
	GDKInput.shutdown()
	GDKAchievements.shutdown()
	GDK.shutdown()
	print("[GDK] Shut down cleanly")
