extends Node
## Autoload script that initializes GDK at startup and manages lifecycle.
## Reads configuration from sample_config.cfg (generated by tools/setup_sample.ps1).
## Gracefully skips when C++ GDK singletons are not available (extensions not compiled).

var config := ConfigFile.new()

# Runtime singleton references (null when C++ extensions aren't loaded)
var _gdk: Object = null
var _gdk_user: Object = null
var _gdk_input: Object = null
var _gdk_achievements: Object = null

func _ready() -> void:
	print("=== GodotGDK Bootstrap ===")

	# Resolve singletons — will be null if extensions aren't compiled
	if Engine.has_singleton("GDK"):
		_gdk = Engine.get_singleton("GDK")
	if Engine.has_singleton("GDKUser"):
		_gdk_user = Engine.get_singleton("GDKUser")
	if Engine.has_singleton("GDKInput"):
		_gdk_input = Engine.get_singleton("GDKInput")
	if Engine.has_singleton("GDKAchievements"):
		_gdk_achievements = Engine.get_singleton("GDKAchievements")

	if _gdk == null:
		push_warning("[GDK] C++ GDK extension not loaded — skipping GDK initialization. Build the extension to enable GDK features.")
		return

	print("GDK Version: ", _gdk.get_version())

	# Load sample configuration
	var err = config.load("res://sample_config.cfg")
	if err != OK:
		push_error("[GDK] sample_config.cfg not found! Run tools/setup_sample.ps1 first.")
		return

	# Connect signals
	_gdk.connect("initialized", _on_gdk_initialized)
	_gdk.connect("error_occurred", _on_gdk_error)
	if _gdk_user:
		_gdk_user.connect("user_signed_in", _on_user_signed_in)
		_gdk_user.connect("sign_in_failed", _on_sign_in_failed)
		_gdk_user.connect("user_signed_out", _on_user_signed_out)
	if _gdk_input:
		_gdk_input.connect("device_connected", _on_device_connected)
		_gdk_input.connect("device_disconnected", _on_device_disconnected)

	# Initialize GDK runtime
	err = _gdk.initialize()
	if err != OK:
		push_error("GDK initialization failed: %s" % error_string(err))

func _on_gdk_initialized() -> void:
	print("[GDK] Runtime initialized!")

	# Initialize Xbox Live services with SCID from config
	var scid = config.get_value("xbox_live", "scid", "")
	if scid.is_empty():
		push_warning("[GDK] No SCID configured — achievements will not work")
	elif _gdk_achievements:
		var scid_err = _gdk_achievements.initialize(scid)
		if scid_err == OK:
			print("[GDK] Xbox Live services ready")

	# Initialize GameInput
	if _gdk_input:
		var input_err = _gdk_input.initialize()
		if input_err == OK:
			print("[GDK] GameInput ready, devices: ", _gdk_input.get_connected_device_count())

	# Try silent sign-in
	if _gdk_user:
		_gdk_user.sign_in_silently()

func _on_gdk_error(message: String) -> void:
	push_error("[GDK] Error: " + message)

func _on_user_signed_in(user) -> void:
	print("[GDK] User signed in successfully")

func _on_sign_in_failed(error: String) -> void:
	push_warning("[GDK] Sign-in failed: " + error)

func _on_user_signed_out() -> void:
	print("[GDK] User signed out")

func _on_device_connected(joy_id: int) -> void:
	print("[GDK] Controller connected: joy ", joy_id)

func _on_device_disconnected(joy_id: int) -> void:
	print("[GDK] Controller disconnected: joy ", joy_id)

func _process(_delta: float) -> void:
	if _gdk:
		_gdk.tick()
	if _gdk_input:
		_gdk_input.process()

func _exit_tree() -> void:
	if _gdk_input:
		_gdk_input.shutdown()
	if _gdk_achievements:
		_gdk_achievements.shutdown()
	if _gdk:
		_gdk.shutdown()
	print("[GDK] Shut down cleanly")
