# XBOX Godot Sample Setup
# Generates sample_config.cfg and MicrosoftGame.config from your Partner Center values.

param(
    [string]$ConfigPath = "$PSScriptRoot\..\sample\tutorial_app\sample_config.cfg"
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrEmpty($ConfigPath)) {
    Write-Error "setup_sample.ps1: -ConfigPath cannot be empty."
    exit 1
}

# tutorial_gameinput intentionally has no GDK/PlayFab config — it's a
# standalone GameInput-only sample. If someone points this script at it
# the generated MicrosoftGame.config / sample_config.cfg will be unused
# by the sample but harmless to produce.

function Normalize-TitleId {
    param([string]$Value)

    $normalizedTitleId = $Value.Trim().ToLower()
    if ($normalizedTitleId.StartsWith("0x")) { $normalizedTitleId = $normalizedTitleId.Substring(2) }

    if ([string]::IsNullOrWhiteSpace($normalizedTitleId) -or
            $normalizedTitleId.Length -gt 8 -or
            $normalizedTitleId -notmatch '^[0-9a-f]+$') {
        throw "Title ID must be 1-8 hexadecimal characters (optionally prefixed with 0x)."
    }

    return $normalizedTitleId.PadLeft(8, '0')
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  XBOX Godot Sample Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This script configures the sample project with your Partner Center values."
Write-Host "You can find these in Partner Center (https://partner.microsoft.com/)."
Write-Host ""

# Collect values
Write-Host "--- Xbox Live Settings ---" -ForegroundColor Yellow
$TitleId = Read-Host "Title ID (hex, e.g. 6718942c)"
$MsaAppId = Read-Host "MSA App ID (GUID)"
$StoreId = Read-Host "Store ID (e.g. 9XXXXXXXXX)"
$SandboxId = Read-Host "Sandbox ID (e.g. XDKS.1)"

$NormalizedTitleId = Normalize-TitleId $TitleId
$Scid = "00000000-0000-0000-0000-0000$NormalizedTitleId"
Write-Host "Derived SCID: $Scid" -ForegroundColor DarkGray

Write-Host ""
Write-Host "--- Identity Settings ---" -ForegroundColor Yellow
$GameName = Read-Host "Game name [XBOX Godot Sample Tutorial App]"
if ([string]::IsNullOrWhiteSpace($GameName)) { $GameName = "XBOX Godot Sample Tutorial App" }
$Publisher = Read-Host "Publisher CN (e.g. CN=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)"
$PublisherDisplay = Read-Host "Publisher display name"
$Version = Read-Host "Version [1.0.0.0]"
if ([string]::IsNullOrWhiteSpace($Version)) { $Version = "1.0.0.0" }

Write-Host ""
Write-Host "--- Achievement Settings ---" -ForegroundColor Yellow
$AchievementId = Read-Host "Demo achievement ID [1]"
if ([string]::IsNullOrWhiteSpace($AchievementId)) { $AchievementId = "1" }

# Derive identity name from publisher + game name
$IdentityName = ($Publisher -replace "CN=","") -replace "-",""
$IdentityName = "$IdentityName.$($GameName -replace '\s','')"

# Write sample_config.cfg
$CfgContent = @"
; XBOX Godot Sample Configuration
; Generated by tools/setup_sample.ps1

[xbox_live]
title_id = "$NormalizedTitleId"
msa_app_id = "$MsaAppId"
store_id = "$StoreId"
scid = "$Scid"
sandbox_id = "$SandboxId"

[identity]
game_name = "$GameName"
publisher = "$Publisher"
publisher_display_name = "$PublisherDisplay"
version = "$Version"

[achievements]
demo_achievement_id = "$AchievementId"
"@

$CfgContent | Set-Content -Path $ConfigPath -Encoding UTF8
Write-Host ""
Write-Host "Wrote: $ConfigPath" -ForegroundColor Green

# Write MicrosoftGame.config
$SampleDir = Split-Path $ConfigPath -Parent
$MgcPath = Join-Path $SampleDir "MicrosoftGame.config"
$GodotExe = "Godot_v4.6.1-stable_win64.exe"

$MgcContent = @"
<?xml version="1.0" encoding="utf-8"?>
<Game configVersion="1">
  <Identity Name="$IdentityName"
            Publisher="$Publisher"
            Version="$Version" />

  <TitleId>$NormalizedTitleId</TitleId>
  <MSAAppId>$MsaAppId</MSAAppId>
  <StoreId>$StoreId</StoreId>

  <ExecutableList>
    <Executable Name="$GodotExe"
               TargetDeviceFamily="PC"
               Id="Game"
               IsDevOnly="false" />
  </ExecutableList>

  <ShellVisuals DefaultDisplayName="$GameName"
                PublisherDisplayName="$PublisherDisplay"
                StoreLogo="StoreLogo.png"
                Square150x150Logo="Logo150.png"
                Square44x44Logo="Logo44.png"
                Square480x480Logo="Logo480.png"
                SplashScreenImage="SplashScreen.png"
                ForegroundText="light"
                BackgroundColor="#1a1a2e" />

  <DesktopRegistration>
    <DependencyList>
      <KnownDependency Name="VC14" />
    </DependencyList>
  </DesktopRegistration>
</Game>
"@

$MgcContent | Set-Content -Path $MgcPath -Encoding UTF8
Write-Host "Wrote: $MgcPath" -ForegroundColor Green

# Update export_presets.cfg
$PresetPath = Join-Path $SampleDir "export_presets.cfg"
if (Test-Path $PresetPath) {
    $presetContent = Get-Content $PresetPath -Raw
    $presetContent = $presetContent -replace 'xbox_live/title_id="[^"]*"', "xbox_live/title_id=`"$NormalizedTitleId`""
    $presetContent = $presetContent -replace 'xbox_live/msa_app_id="[^"]*"', "xbox_live/msa_app_id=`"$MsaAppId`""
    $presetContent = $presetContent -replace 'xbox_live/store_id="[^"]*"', "xbox_live/store_id=`"$StoreId`""
    $presetContent = $presetContent -replace 'xbox_live/scid="[^"]*"', "xbox_live/scid=`"$Scid`""
    $presetContent = $presetContent -replace 'dev/sandbox_id="[^"]*"', "dev/sandbox_id=`"$SandboxId`""
    $presetContent = $presetContent -replace 'identity/game_name="[^"]*"', "identity/game_name=`"$GameName`""
    $presetContent = $presetContent -replace 'identity/publisher_name="[^"]*"', "identity/publisher_name=`"$Publisher`""
    $presetContent = $presetContent -replace 'identity/publisher_display_name="[^"]*"', "identity/publisher_display_name=`"$PublisherDisplay`""
    $presetContent = $presetContent -replace 'identity/version="[^"]*"', "identity/version=`"$Version`""
    $presetContent | Set-Content -Path $PresetPath -Encoding UTF8 -NoNewline
    Write-Host "Wrote: $PresetPath" -ForegroundColor Green
}

Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Set your PC sandbox:  XblPCSandbox.exe set $SandboxId"
Write-Host "  2. Build the addon:      cmake --build build --preset debug"
$LaunchScript = Join-Path $SampleDir "launch_editor.bat"
Write-Host "  3. Launch the editor:    $LaunchScript"
Write-Host ""
